### PR TITLE
Test PR comment

### PR DESCRIPTION
**Pull request by samuelburnham**

### CODE REVIEW

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci
Features:
Env vars:
LURK_RC=100,200

**Comment by samuelburnham** [comment]
!gpu-benchmark
Benches:
fibonacci,bench_test
Features:
Env vars:

**Comment by huitseeker** [comment]
!gpu-benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark

**Comment by samuelburnham** [comment]
!benchmark --bench fibonacci
LURK_RC=1000

**Comment by samuelburnham** [comment]
!benchmark --bench fibonacci --bench bench_test --features cuda
LURK_RC=10

**Comment by samuelburnham** [comment]
!benchmark --bench fibonacci

**Pull request closed without merging**
